lmp_config:
  env:
    map_size: 100
    max_plan_iter: 1
    visualize: true
  lmps:
    tabletop_ui:
      prompt_fname: tabletop_ui_prompt
      model: gpt-4.1-nano
      max_tokens: 1024
      temperature: 0
      query_prefix: "# Query: "
      query_suffix: "."
      stop:
        - "# Query: "
        - "objects = "
      maintain_session: false
      include_context: false
      has_return: false
      return_val_name: ret_val
      load_cache: true
      debug_mode: false 
    
    parse_obj_name:
      prompt_fname: parse_obj_name_prompt
      model: gpt-4.1-nano
      max_tokens: 1024 
      temperature: 0
      query_prefix: "# "
      query_suffix: "."
      stop:
        - "#"
        - "objects = ["
      maintain_session: false
      include_context: true
      has_return: true
      return_val_name: ret_val
      debug_mode: true 

    parse_position:
      prompt_fname: parse_position_prompt
      model: gpt-4.1-nano
      max_tokens: 1024 
      temperature: 0
      query_prefix: "# "
      query_suffix: "."
      stop:
        - "#"
      maintain_session: false
      include_context: true
      has_return: true
      return_val_name: ret_val
      debug_mode: true 

    parse_question:
      prompt_fname: parse_question_prompt
      model: gpt-4.1-nano
      max_tokens: 1024 
      temperature: 0
      query_prefix: "# "
      query_suffix: "."
      stop:
        - "#"
        - "objects = ["
      maintain_session: false
      include_context: true
      has_return: true
      return_val_name: ret_val
      debug_mode: true 

    transform_shape_pts:
      prompt_fname: transform_shape_pts_prompt
      model: gpt-4.1-nano
      max_tokens: 1024 
      temperature: 0
      query_prefix: "# "
      query_suffix: "."
      stop:
        - "#"
      maintain_session: false
      include_context: true
      has_return: true
      return_val_name: new_shape_pts
      debug_mode: true 

    fgen:
      prompt_fname: fgen_prompt
      model: gpt-4.1-nano
      max_tokens: 1024
      temperature: 0
      query_prefix: "# define function: "
      query_suffix: "."
      stop:
        - "# define"
        - "# example"
      maintain_session: false
      include_context: false
      return_val_name: ret_val
      load_cache: true
      debug_mode: true 

